### ISSUE TITLE
Generated PDFs have blank first and last pages

### ISSUE THREAD

**Issue by perqa** [mermaidjs/mermaid.cli#26] opened 2018-02-13 12:50 UTC
Not sure whether this is a feature or a bug, but is there any way to avoid those blank pages when generating PDFs?

**Comment by tylerlong** [comment] 2018-02-27 02:45
I was unaware of this issue. Let me do some testing when I have some time.

**Comment by perqa** [comment] 2018-02-27 19:44
As I discovered later, it's when you have flow chart that fits in one single page that you get the extra two blank pages.

**Comment by tylerlong** [comment] 2018-03-15 15:04
I cannot reproduce this issue.  Take this file for example: https://github.com/mermaidjs/mermaid.cli/blob/master/test/flowchart.mmd

```shell
mmdc -i test/flowchart.mmd -o test/flowchart.pdf -t forest
```

generates a PDF file with one and only one page.

Could you please post a sample mermaid file to reproduce the issue?

**Comment by perqa** [comment] 2018-03-18 17:33
I do not have that file anymore. Stupid of me not to attach it to this ticket when I created it. Since you asked I have tried to reproduce it myself, but unsuccessfully so far. I must have hit an odd edge case.

**Comment by tylerlong** [comment] 2018-03-21 13:21
Closing. Feel free to create a new issue if you encounter that odd edge case again.

**Closed by tylerlong** 2018-03-21 13:21 UTC
